# Generated by Django 4.2.29 on 2026-04-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='blogs/'),
        ),
    ]
