# Generated by Django 4.2.29 on 2026-03-31 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(default='-', max_length=20)),
                ('alternative_number', models.CharField(default='-', max_length=20)),
                ('email_address', models.CharField(default='-', max_length=100)),
                ('location', models.CharField(default='-', max_length=50)),
                ('google_pin', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.CharField(blank=True, max_length=10, null=True)),
                ('type_of_dailysis', models.CharField(default='Normal', max_length=200)),
                ('need_help', models.BooleanField(default=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='active', max_length=20)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_account', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
