# Generated by Django 4.2.29 on 2026-03-31 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('role_name', models.TextField(blank=True, null=True)),
                ('added_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='active', max_length=20)),
                ('removed_datetime', models.DateTimeField(blank=True, null=True)),
                ('terms_conditions', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userprofilerole', to=settings.AUTH_USER_MODEL)),
                ('user_added', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userprofilerole_added', to=settings.AUTH_USER_MODEL)),
                ('user_removed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userprofilerole_removed', to=settings.AUTH_USER_MODEL)),
                ('user_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userprofilerole', to='userprofile.role')),
            ],
        ),
    ]
