# Generated by Django 4.2.29 on 2026-05-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_visitor_session_searchevent_pageview_funnelevent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funnelevent',
            options={'ordering': ['funnel_name', 'step_number', 'timestamp']},
        ),
        migrations.RenameField(
            model_name='funnelevent',
            old_name='step',
            new_name='step_name',
        ),
        migrations.AddField(
            model_name='funnelevent',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funnelevent',
            name='step_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='funnelevent',
            index=models.Index(fields=['funnel_name', 'step_number'], name='userprofile_funnel__026148_idx'),
        ),
        migrations.AddIndex(
            model_name='funnelevent',
            index=models.Index(fields=['visitor', 'session'], name='userprofile_visitor_9cdd79_idx'),
        ),
    ]
