# Generated by Django 4.2.29 on 2026-05-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_funnelevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
