# Generated by Django 4.2.29 on 2026-04-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='code',
            field=models.CharField(default='001', max_length=10),
        ),
    ]
