# Generated by Django 4.2.29 on 2026-04-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_county_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituent',
            name='county',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='ward',
            name='constituent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ward',
            name='county',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
