# Generated by Django 4.2.29 on 2026-04-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_constituent_county_alter_ward_constituent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='index',
            field=models.IntegerField(default=47),
        ),
    ]
