# Generated by Django 4.2.29 on 2026-04-29 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0004_county_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('cover', models.CharField(default='No', max_length=50)),
                ('image', models.FileField(blank=True, null=True, upload_to='hospitalimage/%Y/%m/%d/)/%Y/%m/%d/')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='active', max_length=20)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalimage', to='hospital.hospital')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalimage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
