# Generated by Django 4.2.29 on 2026-04-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_hospitalimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='hospital/%Y/%m/%d/)/%Y/%m/%d/'),
        ),
    ]
