# Generated by Django 4.2.29 on 2026-05-01 10:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_hospital_latitude_hospital_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='active', max_length=20)),
                ('name', models.CharField(max_length=250)),
                ('mobile_number', models.CharField(max_length=20)),
                ('appointment_date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='hospital.hospital')),
            ],
        ),
    ]
