# Generated by Django 4.2.29 on 2026-05-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_publicholiday_operationday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='google_pin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
