# Generated by Django 4.2.29 on 2026-03-31 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(default='-', max_length=20)),
                ('alternative_number', models.CharField(default='-', max_length=20)),
                ('email_address', models.CharField(default='-', max_length=100)),
                ('location', models.CharField(default='-', max_length=50)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('license', models.FileField(blank=True, null=True, upload_to='license/%Y/%m/%d')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='active', max_length=20)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_account', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
