# Generated by Django 4.2.29 on 2026-05-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='title',
            field=models.CharField(default='DR.', max_length=250),
        ),
    ]
