# Generated by Django 4.2.29 on 2026-05-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_hospital_doctor_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profile/%Y/%m/%d'),
        ),
    ]
